name: Alpaca Daily Trading

on:
  schedule:
    - cron: '30 13 * * 1-5'  # Every weekday at 1:30 PM UTC (9:30 AM ET)
  workflow_dispatch:

jobs:
  run-alpaca-trade:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install alpaca-py pandas requests

      - name: Upgrade alpaca-py
        run: |
          pip install --upgrade alpaca-py

      - name: Run trading script
        env:
          ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
          ALPACA_API_SECRET: ${{ secrets.ALPACA_API_SECRET }}
        run: |
          python alpaca_live_trading.py
