name: Daily Signal Update

on:
  schedule:
    - cron: '0 12 * * *'  # runs daily at 12:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install yfinance pandas scikit-learn xgboost numpy imbalanced-learn ta requests alpaca-py

      - name: Run prediction and upload script
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          python make_predictions.py

